### ISSUE TITLE
Panic during the test run

### ISSUE THREAD

**Issue by alexeyklyukin** [ikitiki/logical_backup#48]
I still have the files from that run and looking into this.
```
------------- Backup  --------------
2019/01/09 18:02:41 No staging directory. Writing directly to the archive dir
2019/01/09 18:02:41 Archive directory: "/tmp/final"
2019/01/09 18:02:41 BackupThreshold: 100
2019/01/09 18:02:41 DeltasPerFile: 10000
2019/01/09 18:02:41 DB connection string: @/tmp:0/lb_test1 slot:"testslot" publication:"mypub"
2019/01/09 18:02:41 Backing up new tables: true
2019/01/09 18:02:41 Fsync: true
2019/01/09 18:02:41 Force new basebackup of a modified table after inactivity for: 24h0m0s
2019/01/09 18:02:41 Pg backend session PID: 65228
2019/01/09 18:02:41 created missing publication: "create publication \"mypub\" for all tables"
2019/01/09 18:02:41 Creating logical replication slot testslot
2019/01/09 18:02:41 Created missing replication slot "testslot", consistent point 0/102CDBA8
2019/01/09 18:02:41 Queueing tables for the initial backup
2019/01/09 18:02:41 Starting 5 background backupers
2019/01/09 18:02:41 background base backuper 4: backing up table "public"."test"
2019/01/09 18:02:41 Starting from 0/102CDBA7 lsn
2019/01/09 18:02:41 Starting base backup of "public"."test"
2019/01/09 18:02:41 table test seems to have no rows; skipping
2019/01/09 18:02:41 "public"."test" backed up in 0s; start lsn: 0/102CFB40, first delta lsn to keep: 0/102CDC48
2019/01/09 18:02:41 Purging segments in /tmp/final/e3/47/00/18403/deltas before the LSN 0/102CDC48
2019/01/09 18:02:42 flushed current segment to disk file /tmp/final/e3/47/00/18403/deltas/00000000102cdc48 and set flush LSN to 0/10355838
2019/01/09 18:02:42 advanced flush LSN to 0/10355838
2019/01/09 18:02:42 sending new status with 0/10355838 flush lsn (i:865 u:1644 d:825 b:0.39Mb)
2019/01/09 18:02:45 flushed current segment to disk file /tmp/final/e3/47/00/18403/deltas/0000000010355918 and set flush LSN to 0/103DCDE0
2019/01/09 18:02:45 advanced flush LSN to 0/103DCDE0
2019/01/09 18:02:45 sending new status with 0/103DCDE0 flush lsn (i:864 u:1646 d:823 b:0.39Mb)
2019/01/09 18:02:45 received WAL message with LSN 0/103DCE50 that is lower or equal to the flush LSN 0/103DCDE0, skipping
2019/01/09 18:02:45 received WAL message with LSN 0/103DCE50 that is lower or equal to the flush LSN 0/103DCDE0, skipping
transaction type: pgbench.sql
scaling factor: 1
query mode: simple
number of clients: 2
number of threads: 2
duration: 5 s
number of transactions actually processed: 8217
latency average = 1.218 ms
tps = 1641.615640 (including connections establishing)
tps = 1642.764676 (excluding connections establishing)
-------------- Restore  --------------
2019/01/09 18:02:46 received shutdown request: replication terminated
2019/01/09 18:02:46 quiting background base backuper 4
2019/01/09 18:02:46 quiting background base backuper 3
2019/01/09 18:02:46 prometheus connection closed
2019/01/09 18:02:46 quiting background base backuper 2
2019/01/09 18:02:46 quiting background base backuper 0
2019/01/09 18:02:46 quiting background base backuper 1
2019/01/09 18:02:46 debug http server closed
2019/01/09 18:02:46 writing and archiving current segment to 00000000103dce50 due to the shutdown
2019/01/09 18:02:46 flushed current segment to disk file /tmp/final/e3/47/00/18403/deltas/00000000103dce50 and set flush LSN to 0/10415600
2019/01/09 18:02:46 dump file doesn't exist, skipping
2019/01/09 18:02:46 reading "/tmp/final/e3/47/00/18403/deltas/00000000102cdc48" segment file
2019/01/09 18:02:47 reading "/tmp/final/e3/47/00/18403/deltas/0000000010355918" segment file
2019/01/09 18:02:48 reading "/tmp/final/e3/47/00/18403/deltas/00000000103dce50" segment file
panic: final LSN(0/103DCE80) does not match begin LSN(0/103DCE50)

goroutine 1 [running]:
github.com/ikitiki/logical_backup/pkg/logicalrestore.(*LogicalRestore).applySegmentFile(0xc000517e28, 0xc00034fac0, 0x31, 0x0, 0x0)
	/Users/alexk/src/go/src/github.com/ikitiki/logical_backup/pkg/logicalrestore/logicalrestore.go:232 +0xfab
github.com/ikitiki/logical_backup/pkg/logicalrestore.(*LogicalRestore).applyDeltas(0xc000517e28, 0x0, 0x0)
	/Users/alexk/src/go/src/github.com/ikitiki/logical_backup/pkg/logicalrestore/logicalrestore.go:314 +0x347
github.com/ikitiki/logical_backup/pkg/logicalrestore.(*LogicalRestore).Restore(0xc0001bde28, 0x0, 0x0)
	/Users/alexk/src/go/src/github.com/ikitiki/logical_backup/pkg/logicalrestore/logicalrestore.go:422 +0x3ea
main.main()
	/Users/alexk/src/go/src/github.com/ikitiki/logical_backup/cmd/restore/main.go:61 +0x216
tables are different
```

**Comment by alexeyklyukin** [comment]
First looking into it, dinspect reports two commit records in the file:

```
reading "/tmp/final/e3/47/00/18403/deltas/00000000103dce50" segment file:

update:    relOID:18403 new newValues:['1738', '827', 'fa3a3c407f82377f55c19c5d403335c7']
commit:    LSN:0/103DCE50 Timestamp:2019-01-09T17:02:45Z TxLSN:0/103DCE80
commit:    LSN:0/103DCE80 Timestamp:2019-01-09T17:02:45Z TxLSN:0/103DCEB0
begin:     FinalLSN:0/103DCF50 Timestamp:2019-01-09T17:02:45Z XID:1040575
insert:    relOID:18403 new values:['1740', '8963', '688ffcd6367bd153033e41bcc801f33d']
commit:    LSN:0/103DCF50 Timestamp:2019-01-09T17:02:45Z TxLSN:0/103DCF80
```

The previous file, `/tmp/final/e3/47/00/18403/deltas/0000000010355918`, actually ends with a begin record:
```
begin:     FinalLSN:0/103DCE50 Timestamp:2019-01-09T17:02:45Z XID:1040573
````

This is expected, as files are written once they reach certain number of records without looking at transaction boundaries. We have a begin for `XID 1040573` and the corresponding commit (with the same FinalLSN and the LSN of the begin, i.e. `0/103DCE50`). What is not expected is another commit record for LSN `0/103DCE80` without a corresponding begin.

**Comment by alexeyklyukin** [comment]
I also see the following entries in the backup log above;

```
2019/01/09 18:02:45 received WAL message with LSN 0/103DCE50 that is lower or equal to the flush LSN 0/103DCDE0, skipping
2019/01/09 18:02:45 received WAL message with LSN 0/103DCE50 that is lower or equal to the flush LSN 0/103DCDE0, skipping
```
What could be is that those records were exactly the missing record for the transaction ID 1040574 (we have begin for 1040573 and 1040575 but no records for 1040574 apart from the commit which allegedly belongs to it).

**Comment by alexeyklyukin** [comment]
The message```received WAL message with LSN 0/103DCE50 that is lower or equal to the flush LSN 0/103DCDE0``` would obviously indicate bad math, as `103DCE50` is greater `103DCDE0`; alas, the message itself is wrong, as it shows (erroneously) the LSN of the latest processed message instead of the one being compared.
